packages:
  - packages/*
  - examples/*

catalog:
  "@angular-devkit/architect": ^0.2003.21
  "@angular-devkit/build-angular": ^20.3.21
  "@angular-devkit/core": ^20.3.21
  "@angular/animations": ^20.3.21
  "@angular/cli": ^20.3.21
  "@angular/common": ^20.3.21
  "@angular/compiler": ^20.3.21
  "@angular/compiler-cli": ^20.3.21
  "@angular/core": ^20.3.21
  "@angular/fire": ^20.0.1
  "@angular/forms": ^20.3.21
  "@angular/platform-browser": ^20.3.21
  "@angular/platform-browser-dynamic": ^20.3.21
  "@angular/platform-server": ^20.3.22
  "@angular/router": ^20.3.21
  "@angular/ssr": ^20.3.21
  "@tailwindcss/vite": ^4.1.14
  "@testing-library/jest-dom": ^6.8.0
  "@testing-library/react": ^16.3.0
  "@types/jsdom": ^21.1.7
  "@types/node": ^24.3.1
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@vitest/coverage-v8": ^3.2.4
  "@vitest/ui": ^3.2.4
  "@nanostores/deepmap": ^0.0.1
  "@vitejs/plugin-react": ^5.0.2
  eslint: ^9.35.0
  firebase: ^11.10.0
  jsdom: ^26.1.0
  nanostores: ^1.1.0
  next: 15.5.18
  postcss: ^8.5.10

  prettier: ^3.6.2
  react: 19.2.3
  react-dom: 19.2.3
  react-router: ^7.12.0
  rimraf: ^6.0.1
  rxjs: ^7.8.2
  tailwindcss: ^4.1.13
  tsup: 8.5.0
  typescript: ^5.9.2
  vite: ^7.1.5
  vitest: ^3.2.4
  vitest-tsconfig-paths: ^3.4.1
  zod: 4.1.12
  zone.js: ^0.15.0

catalogs:
  peerDependencies:
    "@angular/fire": ^20
    firebase: ^11 || ^12
    react: ^19
    react-dom: ^19

onlyBuiltDependencies:
  - "@firebase/util"
  - "@parcel/watcher"
  - esbuild
  - lmdb
  - msgpackr-extract
  - msw
  - protobufjs
  - sharp
  - unrs-resolver

allowBuilds:
  "@firebase/util": true
  "@parcel/watcher": true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  msw: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

gitChecks: false
