import { registerLocale } from "@firebase-oss/ui-translations";

export const pirate = registerLocale("pirate", {
  errors: {
    userNotFound: "Arrr! No account found with this email address, matey",
    wrongPassword: "Arrr! Incorrect password, ye scallywag",
    invalidEmail: "Avast! Enter a valid email address, ye bilge rat",
    userDisabled: "This account has been marooned, arrr!",
    networkRequestFailed: "Can't connect to the server, ye land lubber! Check yer internet connection",
    tooManyRequests: "Too many failed attempts, ye scurvy dog! Try again later",
    missingVerificationCode: "Enter the verification code, ye scallywag",
    emailAlreadyInUse: "An account already exists with this email, arrr!",
    invalidCredential: "The credentials ye provided be invalid, matey",
    weakPassword: "Ye password ain't long enough! It should be at least 8 characters",
    unverifiedEmail: "Verify yer email address to continue, ye scallywag",
    operationNotAllowed: "This operation ain't allowed, arrr! Contact support, matey",
    invalidPhoneNumber: "The phone number be invalid, ye bilge rat",
    missingPhoneNumber: "Provide a phone number, ye scallywag",
    quotaExceeded: "SMS quota exceeded, arrr! Try again later, matey",
    codeExpired: "The verification code has expired, ye scurvy dog",
    captchaCheckFailed: "reCAPTCHA verification failed, arrr! Try again, matey",
    missingVerificationId: "Complete the reCAPTCHA verification first, ye scallywag",
    missingEmail: "Provide an email address, ye bilge rat",
    invalidActionCode: "The password reset link be invalid or has expired, arrr!",
    credentialAlreadyInUse: "An account already exists with this email, arrr! Sign in with that account, matey",
    requiresRecentLogin: "This operation requires a recent login, ye scallywag! Sign in again",
    providerAlreadyLinked: "This phone number be already linked to another account, arrr!",
    invalidVerificationCode: "Invalid verification code, ye scurvy dog! Try again",
    unknownError: "An unexpected error occurred, arrr!",
    popupClosed: "The sign-in popup was closed, ye scallywag! Try again",
    accountExistsWithDifferentCredential:
      "An account already exists with this email, arrr! Sign in with the original provider, matey",
    displayNameRequired: "Provide a display name, ye bilge rat",
    secondFactorAlreadyInUse: "This phone number be already enrolled with this account, arrr!",
  },
  messages: {
    passwordResetEmailSent: "Password reset email sent successfully, arrr!",
    signInLinkSent: "Sign-in link sent successfully, matey!",
    verificationCodeFirst: "Request a verification code first, ye scallywag",
    checkEmailForReset: "Check yer email for password reset instructions, ye bilge rat",
    dividerOr: "or",
    termsAndPrivacy: "By continuing, ye agree to our {tos} and {privacy}, arrr!",
    mfaSmsAssertionPrompt:
      "A verification code will be sent to {phoneNumber} to complete the authentication process, matey.",
  },
  labels: {
    emailAddress: "Email Address, ye bilge rat",
    password: "Password, ye scallywag",
    displayName: "Display Name, ye bilge rat",
    forgotPassword: "Forgot Password, ye scallywag?",
    signUp: "Sign Up, Matey",
    signIn: "Sign In, Matey",
    resetPassword: "Reset Password, ye scallywag",
    createAccount: "Create Account, ye bilge rat",
    backToSignIn: "Back to Sign In, ye scallywag",
    signInWithPhone: "Sign in with Phone, ye scallywag",
    phoneNumber: "Phone Number, ye bilge rat",
    verificationCode: "Verification Code, ye scallywag",
    sendCode: "Send Code, ye scallywag",
    verifyCode: "Verify Code, ye scallywag",
    signInWithGoogle: "Sign in with ye Google Account",
    signInWithFacebook: "Sign in with ye Facebook Account",
    signInWithApple: "Sign in with ye Apple Account",
    signInWithMicrosoft: "Sign in with ye Microsoft Account",
    signInWithGitHub: "Sign in with ye GitHub Account",
    signInWithTwitter: "Sign in with ye X Account",
    signInWithYahoo: "Sign in with ye Yahoo Account",
    signInWithEmailLink: "Sign in with Email Link",
    sendSignInLink: "Send Sign-in Link",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    resendCode: "Resend ye Code",
    sending: "Firing...",
    multiFactorEnrollment: "Multi-factor Enrrrrrrollment!",
    multiFactorAssertion: "Multi-factor Authentication, arrr!",
    mfaTotpVerification: "TOTP Verification, arrr!",
    mfaSmsVerification: "SMS Verification, arrr!",
    generateQrCode: "Generate ye QR Code",
  },
  prompts: {
    noAccount: "Don't have an account, ye scallywag?",
    haveAccount: "Already have an account, matey?",
    enterEmailToReset: "Enter yer email address to reset yer password, ye bilge rat",
    signInToAccount: "Sign in to yer account, matey",
    smsVerificationPrompt: "Enter the verification code sent to yer phone number, ye scallywag",
    enterDetailsToCreate: "Enter yer details to create a new account, ye bilge rat",
    enterPhoneNumber: "Enter yer phone number, matey",
    enterVerificationCode: "Enter the verification code, ye scallywag",
    enterEmailForLink: "Enter yer email to receive a sign-in link, ye bilge rat",
    mfaEnrollmentPrompt: "Select a new multi-factor enrollment method, arrr!",
    mfaAssertionPrompt: "Complete the multi-factor authentication process, ye scallywag",
    mfaAssertionFactorPrompt: "Choose a multi-factor authentication method, matey",
    mfaTotpQrCodePrompt: "Scan this QR code with yer authenticator app, ye bilge rat",
    mfaTotpEnrollmentVerificationPrompt: "Add the code generated by yer authenticator app, arrr!",
  },
});
