#!/usr/bin/env node

/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { readdir, readFile, writeFile, mkdir } from "fs/promises";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { exec } from "child_process";
import { promisify } from "util";

const execAsync = promisify(exec);

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const CORE_BRANDS_DIR = join(__dirname, "../core/brands");
const ANGULAR_LOGOS_DIR = join(__dirname, "src/lib/components/logos");

// Convert brand name to PascalCase for component names
function toPascalCase(str: string): string {
  return str
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

// Convert brand name to kebab-case for file names
function toKebabCase(str: string): string {
  return str.toLowerCase().replace(/\s+/g, "-");
}

// Format generated files with Prettier
async function formatWithPrettier(filePath: string): Promise<void> {
  try {
    // Run prettier from the root directory to use the root prettier config
    const rootDir = join(__dirname, "../../");
    await execAsync(`cd "${rootDir}" && pnpm prettier --write "${filePath}"`);
  } catch (error) {
    console.warn(`⚠️  Failed to format ${filePath}: ${error instanceof Error ? error.message : "Unknown error"}`);
  }
}

// Generate Angular component template from SVG content
function generateComponentTemplate(brandName: string, svgContent: string): string {
  const componentName = toPascalCase(brandName);
  const selector = `fui-${toKebabCase(brandName)}-logo`;

  // Clean up the SVG content - remove width/height attributes and add our class
  // and add the fui-provider__icon class
  const cleanedSvg = svgContent
    .replace(/\s+width="[^"]*"/g, "")
    .replace(/\s+height="[^"]*"/g, "")
    .replace(/<svg([^>]*)>/, '<svg$1 class="fui-provider__icon">');

  return `/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED BY generate-logos.ts

import { Component, input } from "@angular/core";

@Component({
  selector: "${selector}",
  standalone: true,
  template: \`
${cleanedSvg}
  \`,
})
/**
 * The ${componentName} logo SVG component.
 */
export class ${componentName}LogoComponent {
  /** The width of the logo. */
  width = input<string | number>("1em");
  /** The height of the logo. */
  height = input<string | number>("1em");
  /** Optional additional CSS class names. */
  className = input<string>("");
}
`;
}

// Main function to generate logo components
async function generateLogoComponents(): Promise<void> {
  try {
    console.log("🎨 Generating Angular logo components from core SVG files...");

    // Ensure the logos directory exists
    await mkdir(ANGULAR_LOGOS_DIR, { recursive: true });

    // Read all brand directories
    const brandDirs = await readdir(CORE_BRANDS_DIR, { withFileTypes: true });
    const brandDirectories = brandDirs.filter((dirent) => dirent.isDirectory());

    console.log(`📁 Found ${brandDirectories.length} brand directories`);

    for (const brandDir of brandDirectories) {
      const brandName = brandDir.name;
      const brandPath = join(CORE_BRANDS_DIR, brandName);

      try {
        // Look for logo.svg in the brand directory
        const logoPath = join(brandPath, "logo.svg");
        const svgContent = await readFile(logoPath, "utf-8");

        // Generate the component
        const componentContent = generateComponentTemplate(brandName, svgContent);

        // Write the component file
        const componentFileName = `${toKebabCase(brandName)}.ts`;
        const componentPath = join(ANGULAR_LOGOS_DIR, componentFileName);

        await writeFile(componentPath, componentContent, "utf-8");
        
        // Format the generated file with Prettier
        await formatWithPrettier(componentPath);

        console.log(`✅ Generated ${brandName} logo component: ${componentFileName}`);
      } catch (error) {
        console.warn(`⚠️  Skipping ${brandName}: ${error instanceof Error ? error.message : "Unknown error"}`);
      }
    }

    // Generate an index file to export all components
    const indexContent = `/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

${brandDirectories
      .map((brandDir) => {
        const brandName = brandDir.name;
        const componentName = toPascalCase(brandName);
        const fileName = toKebabCase(brandName);
        return `export { ${componentName}LogoComponent } from './${fileName}';`;
      })
      .join("\n")}
`;

    const indexPath = join(ANGULAR_LOGOS_DIR, "index.ts");
    await writeFile(indexPath, indexContent, "utf-8");
    
    // Format the index file with Prettier
    await formatWithPrettier(indexPath);

    console.log("📄 Generated index.ts file");
    console.log("🎉 Logo component generation complete!");
  } catch (error) {
    console.error("❌ Error generating logo components:", error);
    process.exit(1);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  generateLogoComponents();
}
