/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'firebaseui';


interface PasswordEmailFormProps {
  
  /**  */
  state?: Components.PasswordEmailForm["state"]
}

interface PasswordEmailFormEvents {
  
}

interface PasswordEmailFormSlots {
  default: any
}
  
/* generated by Svelte v3.34.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let password_email_form;
	let current;
	const default_slot_template = /*#slots*/ ctx[4].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[3], null);

	return {
		c() {
			password_email_form = element("password-email-form");
			if (default_slot) default_slot.c();
			set_custom_element_data(password_email_form, "state", /*state*/ ctx[0]);
		},
		m(target, anchor) {
			insert(target, password_email_form, anchor);

			if (default_slot) {
				default_slot.m(password_email_form, null);
			}

			/*password_email_form_binding*/ ctx[5](password_email_form);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 8) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[3], dirty, null, null);
				}
			}

			if (!current || dirty & /*state*/ 1) {
				set_custom_element_data(password_email_form, "state", /*state*/ ctx[0]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(password_email_form);
			if (default_slot) default_slot.d(detaching);
			/*password_email_form_binding*/ ctx[5](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { state = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(1, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function password_email_form_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(1, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("state" in $$props) $$invalidate(0, state = $$props.state);
		if ("$$scope" in $$props) $$invalidate(3, $$scope = $$props.$$scope);
	};

	return [state, __ref, getWebComponent, $$scope, slots, password_email_form_binding];
}

class PasswordEmailForm extends SvelteComponent {
  $$prop_def: PasswordEmailFormProps;
  $$events_def: PasswordEmailFormEvents;
  $$slot_def: PasswordEmailFormSlots;

  $on<K extends keyof PasswordEmailFormEvents>(type: K, callback: (e: PasswordEmailFormEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<PasswordEmailFormProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { state: 0, getWebComponent: 2 });
	}

	get getWebComponent(): HTMLPasswordEmailFormElement | undefined {
		return this.$$.ctx[2];
	}
}

export default PasswordEmailForm;