/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FirebaseAuth, UserCredential } from "@firebase/auth-types";
export namespace Components {
    interface AnonymousAuthButton {
    }
    interface AppleAuthButton {
    }
    interface FacebookAuthButton {
    }
    interface FirebaseSignInForm {
        "assetBasePath": string;
        /**
          * Whether to automatically upgrade existing anonymous users on sign-in/sign-up. See Upgrading anonymous users.
         */
        "autoUpgradeAnonymousUsers": boolean;
        /**
          * The URL of the Privacy Policy page.
         */
        "privacyPolicyUrl": string | undefined;
        "setAuth": (auth: FirebaseAuth) => Promise<void>;
        "signInSuccessUrl": string | undefined;
        /**
          * The URL of the Terms of Service page.
         */
        "tosUrl": string | undefined;
    }
    interface GithubAuthButton {
    }
    interface GoogleAuthButton {
    }
    interface MicrosoftAuthButton {
    }
    interface PasswordEmailForm {
        "state": any;
    }
    interface TwitterAuthButton {
    }
}
declare global {
    interface HTMLAnonymousAuthButtonElement extends Components.AnonymousAuthButton, HTMLStencilElement {
    }
    var HTMLAnonymousAuthButtonElement: {
        prototype: HTMLAnonymousAuthButtonElement;
        new (): HTMLAnonymousAuthButtonElement;
    };
    interface HTMLAppleAuthButtonElement extends Components.AppleAuthButton, HTMLStencilElement {
    }
    var HTMLAppleAuthButtonElement: {
        prototype: HTMLAppleAuthButtonElement;
        new (): HTMLAppleAuthButtonElement;
    };
    interface HTMLFacebookAuthButtonElement extends Components.FacebookAuthButton, HTMLStencilElement {
    }
    var HTMLFacebookAuthButtonElement: {
        prototype: HTMLFacebookAuthButtonElement;
        new (): HTMLFacebookAuthButtonElement;
    };
    interface HTMLFirebaseSignInFormElement extends Components.FirebaseSignInForm, HTMLStencilElement {
    }
    var HTMLFirebaseSignInFormElement: {
        prototype: HTMLFirebaseSignInFormElement;
        new (): HTMLFirebaseSignInFormElement;
    };
    interface HTMLGithubAuthButtonElement extends Components.GithubAuthButton, HTMLStencilElement {
    }
    var HTMLGithubAuthButtonElement: {
        prototype: HTMLGithubAuthButtonElement;
        new (): HTMLGithubAuthButtonElement;
    };
    interface HTMLGoogleAuthButtonElement extends Components.GoogleAuthButton, HTMLStencilElement {
    }
    var HTMLGoogleAuthButtonElement: {
        prototype: HTMLGoogleAuthButtonElement;
        new (): HTMLGoogleAuthButtonElement;
    };
    interface HTMLMicrosoftAuthButtonElement extends Components.MicrosoftAuthButton, HTMLStencilElement {
    }
    var HTMLMicrosoftAuthButtonElement: {
        prototype: HTMLMicrosoftAuthButtonElement;
        new (): HTMLMicrosoftAuthButtonElement;
    };
    interface HTMLPasswordEmailFormElement extends Components.PasswordEmailForm, HTMLStencilElement {
    }
    var HTMLPasswordEmailFormElement: {
        prototype: HTMLPasswordEmailFormElement;
        new (): HTMLPasswordEmailFormElement;
    };
    interface HTMLTwitterAuthButtonElement extends Components.TwitterAuthButton, HTMLStencilElement {
    }
    var HTMLTwitterAuthButtonElement: {
        prototype: HTMLTwitterAuthButtonElement;
        new (): HTMLTwitterAuthButtonElement;
    };
    interface HTMLElementTagNameMap {
        "anonymous-auth-button": HTMLAnonymousAuthButtonElement;
        "apple-auth-button": HTMLAppleAuthButtonElement;
        "facebook-auth-button": HTMLFacebookAuthButtonElement;
        "firebase-sign-in-form": HTMLFirebaseSignInFormElement;
        "github-auth-button": HTMLGithubAuthButtonElement;
        "google-auth-button": HTMLGoogleAuthButtonElement;
        "microsoft-auth-button": HTMLMicrosoftAuthButtonElement;
        "password-email-form": HTMLPasswordEmailFormElement;
        "twitter-auth-button": HTMLTwitterAuthButtonElement;
    }
}
declare namespace LocalJSX {
    interface AnonymousAuthButton {
    }
    interface AppleAuthButton {
    }
    interface FacebookAuthButton {
    }
    interface FirebaseSignInForm {
        "assetBasePath"?: string;
        /**
          * Whether to automatically upgrade existing anonymous users on sign-in/sign-up. See Upgrading anonymous users.
         */
        "autoUpgradeAnonymousUsers"?: boolean;
        "onSignInSuccessful"?: (event: CustomEvent<UserCredential>) => void;
        /**
          * The URL of the Privacy Policy page.
         */
        "privacyPolicyUrl"?: string | undefined;
        "signInSuccessUrl"?: string | undefined;
        /**
          * The URL of the Terms of Service page.
         */
        "tosUrl"?: string | undefined;
    }
    interface GithubAuthButton {
    }
    interface GoogleAuthButton {
    }
    interface MicrosoftAuthButton {
    }
    interface PasswordEmailForm {
        "state"?: any;
    }
    interface TwitterAuthButton {
    }
    interface IntrinsicElements {
        "anonymous-auth-button": AnonymousAuthButton;
        "apple-auth-button": AppleAuthButton;
        "facebook-auth-button": FacebookAuthButton;
        "firebase-sign-in-form": FirebaseSignInForm;
        "github-auth-button": GithubAuthButton;
        "google-auth-button": GoogleAuthButton;
        "microsoft-auth-button": MicrosoftAuthButton;
        "password-email-form": PasswordEmailForm;
        "twitter-auth-button": TwitterAuthButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "anonymous-auth-button": LocalJSX.AnonymousAuthButton & JSXBase.HTMLAttributes<HTMLAnonymousAuthButtonElement>;
            "apple-auth-button": LocalJSX.AppleAuthButton & JSXBase.HTMLAttributes<HTMLAppleAuthButtonElement>;
            "facebook-auth-button": LocalJSX.FacebookAuthButton & JSXBase.HTMLAttributes<HTMLFacebookAuthButtonElement>;
            "firebase-sign-in-form": LocalJSX.FirebaseSignInForm & JSXBase.HTMLAttributes<HTMLFirebaseSignInFormElement>;
            "github-auth-button": LocalJSX.GithubAuthButton & JSXBase.HTMLAttributes<HTMLGithubAuthButtonElement>;
            "google-auth-button": LocalJSX.GoogleAuthButton & JSXBase.HTMLAttributes<HTMLGoogleAuthButtonElement>;
            "microsoft-auth-button": LocalJSX.MicrosoftAuthButton & JSXBase.HTMLAttributes<HTMLMicrosoftAuthButtonElement>;
            "password-email-form": LocalJSX.PasswordEmailForm & JSXBase.HTMLAttributes<HTMLPasswordEmailFormElement>;
            "twitter-auth-button": LocalJSX.TwitterAuthButton & JSXBase.HTMLAttributes<HTMLTwitterAuthButtonElement>;
        }
    }
}
