/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED BY generate-logos.ts

import { Component, input } from "@angular/core";

@Component({
  selector: "fui-twitter-logo",
  standalone: true,
  template: `
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 30" fill="currentColor" class="fui-provider__icon">
      <path
        d="M26.37,26l-8.795-12.822l0.015,0.012L25.52,4h-2.65l-6.46,7.48L11.28,4H4.33l8.211,11.971L12.54,15.97L3.88,26h2.65 l7.182-8.322L19.42,26H26.37z M10.23,6l12.34,18h-2.1L8.12,6H10.23z"
      />
    </svg>
  `,
})
/**
 * The Twitter logo SVG component.
 */
export class TwitterLogoComponent {
  /** The width of the logo. */
  width = input<string | number>("1em");
  /** The height of the logo. */
  height = input<string | number>("1em");
  /** Optional additional CSS class names. */
  className = input<string>("");
}
