/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// GENERATED BY generate-logos.ts

import { Component, input } from "@angular/core";

@Component({
  selector: "fui-yahoo-logo",
  standalone: true,
  template: `
    <svg
      fill="#5F01D1"
      version="1.1"
      id="Layer_1"
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      viewBox="-271 324 256 153"
      xml:space="preserve"
      class="fui-provider__icon"
    >
      <g>
        <path
          d="M-37.5,356.3c0.1,0,0.2,0,0.2,0l7.1-10.3c-0.1,0-0.3,0-0.4,0l0.7-1.1h-99.9l3.9,15.7h27.3l-46,41.5
		c-9.4-13-31.4-39.9-46.7-62.3h34.4v-12l0.4-2.6c-0.1,0-0.3-0.1-0.4-0.1V324H-271v15.8h33.8c13.1,10.3,63.4,73,65.4,79.2
		c0.8,5.9,1.6,40.4-0.9,43c-4.9,5.2-27.5,3.8-32.9,4.2l-1.9,10.7c9.9,0.3,42.2-0.8,52.2-0.8c19.8,0,54.4-0.1,59.3,0.3l0.6-11.2
		c-5-0.8-32.3-0.1-36-1c-0.8-5.4-1.7-41.8-0.9-45.6c3.9-10.9,61.2-55.1,67.5-56.8c1.4-0.3,3.5-0.8,5.9-1.3h18.5L-37.5,356.3z"
        />
        <path d="M-48.2,447.8l15.3,1.2l17.9-69c-3-0.1-30.1-2.7-33.6-3.3L-48.2,447.8z" />
        <polygon points="-50.8,458.9 -50.7,475.7 -43,476.4 -34.6,477 -32.1,460.5 -41,460.1 	" />
      </g>
    </svg>
  `,
})
/**
 * The Yahoo logo SVG component.
 */
export class YahooLogoComponent {
  /** The width of the logo. */
  width = input<string | number>("1em");
  /** The height of the logo. */
  height = input<string | number>("1em");
  /** Optional additional CSS class names. */
  className = input<string>("");
}
