/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { Metadata } from "next";
import Script from "next/script";
import { FirebaseUIProviderHoc } from "../lib/firebase/ui";
import { ThemeToggle } from "../lib/components/theme-toggle";
import { PirateToggle } from "../lib/components/pirate-toggle";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="dark:bg-neutral-900 dark:text-white" suppressHydrationWarning>
        <Script
          id="dark-mode-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              !(function() {
                try {
                  var theme = localStorage.getItem('theme');
                  var isDark = theme === 'dark' || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches);
                  if (isDark) {
                    document.documentElement.classList.add('dark');
                  }
                  // Mark theme as loaded - this removes the visibility:hidden
                  document.documentElement.classList.add('theme-loaded');
                } catch (e) {
                  // If anything fails, still show content
                  document.documentElement.classList.add('theme-loaded');
                }
              })();
            `,
          }}
        />
        <FirebaseUIProviderHoc>
          <ThemeToggle />
          <PirateToggle />
          {children}
        </FirebaseUIProviderHoc>
      </body>
    </html>
  );
}
